language: node_js
node_js:
- '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_script: node ./scripts/tag-update $TRAVIS_TAG
before_deploy: npm run prepare-github-pages
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: alisahinozcelik@gmail.com
    api_key:
      secure: H8rRUaAB1P0sfRyhV58GxEemWtVcqe8u6vx0Hm4zEeZFckIyI7sYNUMsFWsGLbc9FHVDCwI90n3ijD/kMhHJulOz1EYPJoBjW876tFTaGyr5Sy6sy+AQPYAo/NlVVTJkoc6j3v8BCPpJoSIgFkVHIt2u/95a7a26PEKhh15ZXDmP60i8/u7jjMDMqHNcU5E5Cb5zEWLC18NTtGgzVVvQH4BCNKD33zLCJZlFBLQVvTS3UY97GLb0XrpqrcAp82f1xQPFXuIEDWh1pxFwp86StkZ0WlH6j5371nU1w2ncnHD/pnLZRwy6cC0dsxcSOBMdEI1u/X3QC2XqEbeLC5GAa3kuH/b/1DU5tK6BIzaZxJo/aclCr1xYF5i7vvTDnA2pJBX2+1X3AQStLobJqnEfVYT55vCYwBjrDKxg7WIMa771JE1ee9fiFYVc4dV7ufA1/Ii01JzRvUp6Ck5M5Iu66HLknUnZL+Je9C1rPQ9GYLE3veKKAyIh/Km48skU0BoCy+BXuW6W1K8sygOeskeVg8KwqVEOR19QkkFdEzvF40myVcpwmPGxtoWSVnzWlI7Zss/ymAV7uO32CNW43h8lgcX2UGyxmCB6RkBbukPdx/y0IlES9NoelPIvdDLRDxubFV3xsm2d088B0sV+1rtsVbvsI76NB+yOiviDrcn1ZZk=
    on:
      tags: true
      repo: gen-tech/resize-manager
